### PR TITLE
Runs actions, if configured, in branch plans as well as master plans

### PR DESCRIPTION
**Pull request by alindeman**
As part of these changes, I switched to using `CachedPlanManager`, which is recommended for performance if only immutable versions of plans are required.

Feedback welcomed!

### CODE REVIEW

**Comment by HackAttack** [comment]
I don't understand the intent here…the plugin already works on branch builds (in fact that's its main use case). Can you elaborate?

**Comment by alindeman** [comment]
It doesn't seem to be triggering branch plans for me. This is supposed to work out of the box?

**Comment by HackAttack** [comment]
Yes. You have plan branches enabled?

**Comment by alindeman** [comment]
Yah, I did a bit more research and determined the bug only occurs if the configuration for `github-bamboo-status` is saved. Here's my full log of how to reproduce it on a clean Bamboo instance (`atlas-debug`): 

Created a linked repository "test" pointing at https://github.com/alindeman/test with a default branch of master:
screen shot 2015-11-23 at 9 17 46 pm

Set the "test" repository as the default repository for a build plan:
screen shot 2015-11-23 at 9 19 08 pm

Enabled the repository for sending statuses:
screen shot 2015-11-23 at 9 19 45 pm

Ran the plan on master. The status is sent successfully:
```
[INFO] [talledLocalContainer] 2015-11-23 21:20:12,565 INFO [AtlassianEvent::0-BAM::EVENTS:pool-3-thread-6] [AbstractGitHubStatusAction] GitHub status for commit 246943aa430ffb02cb7e35c06c7c30e637c6eb7a (Build) set to SUCCESS.
```

Created a branch plan for the patch1 branch:
screen shot 2015-11-23 at 9 21 49 pm

No status is sent :cry:

Note that the master branch plan key is `AP-SUCCEED`; the branch plan key is `AP-SUCCEED0` (Bamboo creates this automatically).

When I debug the run of the branch build (`AP-SUCCEED0`), the `RepositoryDefinition` of the main repository in the branch plan is _not the same_ as the `RepositoryDefinition` from the main plan. It's not the same `RepositoryDefinition`: it's a different branch, therefore a different `RepositoryDefinition` ID:

abstractgithubstatusaction_java_-_bamboo-github-status_-____src_github_com_hackattack_bamboo-github-status_

Does this make sense? It appears that when a branch plan is created, a new `RepositoryDefinition` is created. It'll have a different ID than the `RepositoryDefinition` on the master plan.

If I do all these steps, but skip the part about navigating to the Miscellaneous tab, checking the **test** repository, and saving the configuration, statuses for the branches are sent successfully. In that case, `configuredRepos` will be `null` and the default (["all `GitHubRepository` instances"](https://github.com/HackAttack/bamboo-github-status/blob/d50e8ae568eafba94b81cb77012590acc17c129b/src/main/java/com/mhackner/bamboo/AbstractGitHubStatusAction.java#L61-L71)) will be used. Again, however, if the Miscellaneous tab is visited and the configuration saved, the list of RepositoryDefinition IDs will only match on the master plan, but not on any branch plans.

**Comment by HackAttack** [comment]
Thanks a lot for this detailed report! I've never been confident about how the configuration works. Will have to look into this.

**Pull request closed without merging**
